// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3sLuqIFYSPcLwi0cVe4V-oScXWkljzZ8',
    appId: '1:973204207797:android:6c0f1680e7fabd366fe6fc',
    messagingSenderId: '973204207797',
    projectId: 'todo-4586f',
    storageBucket: 'todo-4586f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBux3fHRWkwHAIaZe_JzRdykNkQgB_u1lw',
    appId: '1:973204207797:ios:0d802512390f286f6fe6fc',
    messagingSenderId: '973204207797',
    projectId: 'todo-4586f',
    storageBucket: 'todo-4586f.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBux3fHRWkwHAIaZe_JzRdykNkQgB_u1lw',
    appId: '1:973204207797:ios:0d802512390f286f6fe6fc',
    messagingSenderId: '973204207797',
    projectId: 'todo-4586f',
    storageBucket: 'todo-4586f.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
}
